// <auto-generated />
using System;
using MAVN.Service.MaintenanceMode.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Service.MaintenanceMode.MsSqlRepositories.Migrations
{
    [DbContext(typeof(MaintenanceEventContext))]
    [Migration("20190801082416_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAVN.Service.MaintenanceMode.MsSqlRepositories.Entitites.ActiveMaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualStart");

                    b.Property<TimeSpan>("PlannedDuration");

                    b.Property<string>("Reason")
                        .IsRequired();

                    b.Property<string>("Who")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("maintenance");
                });

            modelBuilder.Entity("MAVN.Service.MaintenanceMode.MsSqlRepositories.Entitites.MaintenanceEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("ActualDuration");

                    b.Property<DateTime>("ActualFinish");

                    b.Property<DateTime>("ActualStart");

                    b.Property<TimeSpan>("PlannedDuration");

                    b.Property<string>("Reason")
                        .IsRequired();

                    b.Property<string>("Who")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("maintenance_history");
                });
#pragma warning restore 612, 618
        }
    }
}
