// <auto-generated />
using System;
using MAVN.Service.MaintenanceMode.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.MaintenanceMode.MsSqlRepositories.Migrations
{
    [DbContext(typeof(MaintenanceEventContext))]
    [Migration("20200703070056_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.MaintenanceMode.MsSqlRepositories.Entitites.ActiveMaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ActualStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("PlannedDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Who")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("maintenance");
                });

            modelBuilder.Entity("MAVN.Service.MaintenanceMode.MsSqlRepositories.Entitites.MaintenanceEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<TimeSpan>("ActualDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("ActualFinish")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ActualStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("PlannedDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Who")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("maintenance_history");
                });
#pragma warning restore 612, 618
        }
    }
}
